# Aliases
alias ls="ls --color=always"
alias l="ls -lah"
alias less="less -R"
alias l.="ls -lah | less"
alias p="path"
alias d="du -hd 1 | sort -h"
alias f="find / -name 2>/dev/null"
alias f.="find . -name 2>/dev/null"
alias ..="cd .."
alias ...="cd ../.."
alias gr="git reset"
alias grh="git reset --hard"
alias gd="git diff"
alias ghi="git log -p -W -S"
alias gci="git commit"
alias gcim="git commit -m"
alias gst="git status"
alias gps="git push"
alias gpl="git pull"
alias gco="git checkout"
alias tmux="tmux -2"
alias rsync="rsync --progress"
alias x="startx"
alias tree="tree | less"
